#!/usr/bin/env perl
use warnings;

# rename - Larry's filename fixer (tweaked)
# https://www.oreilly.com/library/view/perl-cookbook/1565922433/ch09s10.html
# licensed under Perl's Artistic License (i think?)

$op = shift or die "Usage: rename expr [files]\n";
chomp(@ARGV = <STDIN>) unless @ARGV;
for (@ARGV) {
    $was = $_;
    eval $op;
    die $@ if $@;
    if ($ENV{DEBUG}) {
        print $was . " => " . $_ . "\n";
        next;
    }
    rename($was,$_) unless $was eq $_;
}
